name: Trigger auto deployment for myspace234dsgh

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/myspace234dsgh-AutoDeployTrigger-5d23f64d-2f4d-4ff8-b203-4549eb0d24c1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYSPACE234DSGH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYSPACE234DSGH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYSPACE234DSGH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryb6v72qek6ssog.azurecr.io
          registryUsername: ${{ secrets.MYSPACE234DSGH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYSPACE234DSGH_REGISTRY_PASSWORD }}
          containerAppName: myspace234dsgh
          resourceGroup: next13onswab10b
          imageToBuild: containerregistryb6v72qek6ssog.azurecr.io/myspace234dsgh:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


